[package]
name = "http-sig-validator"
version = "0.1.0"
authors = ["Diggory Blake <diggsey@googlemail.com>"]
edition = "2018"
workspace = ".."

[dependencies]
http-sig = { path = "..", features = ["openssl"] }
structopt = "0.3"
env_logger = "0.7.1"
log = "0.4.8"
anyhow = "1.0.28"
